apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: wikiarticle-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: article-app
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 50