apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: wiki-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: wiki-app
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 50