apiVersion: v1
kind: Service
metadata:
  name: wiki-service
spec:
  selector:
    app: wiki-app
  ports:
    - name: port1
      protocol: TCP
      port: 80
      targetPort: 80
    - name: port2
      protocol: TCP
      port: 443
      targetPort: 443