apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"galera","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"mariadb-galera","helm.sh/chart":"mariadb-galera-7.4.10","io.portainer.kubernetes.application.name":"galera","io.portainer.kubernetes.application.owner":"admin"},"name":"galera-mariadb-galera","namespace":"db"},"spec":{"ports":[{"name":"mysql","nodePort":null,"port":3306,"targetPort":"mysql"}],"selector":{"app.kubernetes.io/instance":"galera","app.kubernetes.io/name":"mariadb-galera"},"sessionAffinity":"None","type":"ClusterIP"}}
    meta.helm.sh/release-name: galera
    meta.helm.sh/release-namespace: db
  creationTimestamp: "2023-01-09T13:10:09Z"
  labels:
    app.kubernetes.io/instance: galera
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mariadb-galera
    helm.sh/chart: mariadb-galera-7.4.10
    io.portainer.kubernetes.application.name: galera
    io.portainer.kubernetes.application.owner: admin
  name: galera-mariadb-galera
  namespace: db
  resourceVersion: "9574"
  uid: 2abeb94a-01b4-45ca-be4e-537a9a4150d8
spec:
  clusterIP: 10.152.183.43
  clusterIPs:
  - 10.152.183.43
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: mysql
    nodePort: 32222
  selector:
    app.kubernetes.io/instance: galera
    app.kubernetes.io/name: mariadb-galera
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}